# Generated by Django 2.0 on 2017-12-22 16:26

from django.db import migrations, models
import django.db.models.deletion
import editor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=8)),
                ('Description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField(max_length=256)),
                ('Weight', editor.models.IntegerRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Threat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Identifier', models.CharField(max_length=4, unique=True)),
                ('Title', models.CharField(blank=True, max_length=60)),
                ('Description', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDriver',
            fields=[
                ('driver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.Driver')),
            ],
            bases=('editor.driver',),
        ),
        migrations.CreateModel(
            name='ComplianceDriver',
            fields=[
                ('driver_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.Driver')),
            ],
            bases=('editor.driver',),
        ),
        migrations.CreateModel(
            name='L1StrategicalThreat',
            fields=[
                ('threat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.Threat')),
                ('RiskDriver', models.ManyToManyField(blank=True, to='editor.Driver')),
            ],
            bases=('editor.threat',),
        ),
        migrations.CreateModel(
            name='L2TacticalThreat',
            fields=[
                ('threat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.Threat')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.L1StrategicalThreat')),
            ],
            bases=('editor.threat',),
        ),
        migrations.CreateModel(
            name='L3OperationalThreat',
            fields=[
                ('threat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='editor.Threat')),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.L2TacticalThreat')),
            ],
            bases=('editor.threat',),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='L3OperationalThreat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.L3OperationalThreat'),
        ),
    ]
