# Generated by Django 2.0 on 2018-01-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threat',
            old_name='Identifier',
            new_name='Classifier',
        ),
    ]
