# Generated by Django 2.0 on 2018-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_auto_20180102_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threat',
            name='Classifier',
            field=models.CharField(max_length=4),
        ),
    ]
