# Generated by Django 2.0 on 2018-01-03 16:09

from django.db import migrations
import editor.models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_auto_20180102_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigation',
            name='L3OperationalThreat',
        ),
        migrations.AddField(
            model_name='l3operationalthreat',
            name='Coverage',
            field=editor.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='l3operationalthreat',
            name='Effectiveness',
            field=editor.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='l3operationalthreat',
            name='Implementation',
            field=editor.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mitigation',
        ),
    ]
