# Generated by Django 2.0 on 2018-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20180103_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Identifier',
        ),
        migrations.AddField(
            model_name='driver',
            name='Classifier',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='Title',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
