# Generated by Django 2.0 on 2018-01-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_auto_20180103_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitycontrol',
            name='Description',
            field=models.TextField(max_length=512),
        ),
        migrations.AlterField(
            model_name='securityperimeter',
            name='Description',
            field=models.TextField(max_length=512),
        ),
    ]
